# StyLua configuration for claude-code.nvim

column_width = 100
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 1
quote_style = "AutoPreferDouble"
call_parentheses = "Always"

[sort_requires]
enabled = true